---
- hosts: server
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Nginx Install 
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Copiando index.html personalizado
    copy:
      src: index.html
      dest: /var/www/html/index.html
  
  # - name: restart nginx
  #   service:
  #     name: nginx
  #     state: restarted
      
        #  - modulo service
        #   ----
        #   ---
        #  - modulo copy 
        #  -----
        #  handlers: 
        #  - name: Restart
        #    service:
        #      name: nginx
        #      state: restart
        #